# -*- coding: utf-8 -*-
"""Weather

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P2ZOP35Vw7Ce2l8iLtciwGUYfBOJUU2M
"""

import requests

from datetime import  datetime

api_key = 'eedd28540841275417d9622fbff942d2'
location = input("enter the city name:")
  
complete_api_link ="https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data ['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
data_time = datetime.now().strftime("%d %b %Y |  %I:%M;%S %p ")

print("-----------------------------------------------------------------")
print ("weather stats for -{} || {}". format(location.upper(),data_time))
print("-----------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc : ",weather_desc)
print ("Current humidity: ",hmdt,'%')
print ("Current wind speed : ",wind_spd,'kmph')